name: Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: "pip install -e '.[dev]'"
      - run: ruff .

  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: "pip install -e '.[dev]'"
      - run: mypy .

  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: "pip install -e '.[dev]'"
      - run: black --check .

  examples:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: "pip install -e '.[dev]'"
      - run: make -C tests html
